# Generated by Django 5.0 on 2024-01-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_shortlink_shortened_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='original_link',
            field=models.URLField(error_messages={'max_length': 'Ссылка должна быть не длиннее 250 символов.'}, max_length=250),
        ),
    ]
